### ISSUE TITLE
AppMap pruning retains unique edges by default

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/models-js#23]
An option exists to change the behavior of `prune` such that:
- Unique calls from arbitrary method `ClassA#method` to arbitrary method `ClassB#method` are retained at least once in order to prevent loss of accurate relationship information.
- The count of calls from `ClassA#methodA` to `ClassB#methodB` is exposed in the final AppMap
- The option defaults to enabled

**Comment by kgilpin** [comment]
After discussion, it seems that this is not needed after all.
